[package]
name = "obj2cad-curves"
description = "Recognize cylinders, cones, spheres and tori in obj2cad meshes, strictly"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
obj2cad-core.workspace = true
obj2cad-acis.workspace = true

