[package]
name = "obj2cad-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "obj2cad"
path = "src/main.rs"

[dependencies]
obj2cad-core.workspace = true
obj2cad-dxf.workspace = true
obj2cad-dwg.workspace = true
obj2cad-acis.workspace = true
obj2cad-curves.workspace = true
serde_json.workspace = true
zip = { version = "7", default-features = false, features = ["deflate-flate2"] }
