"""Generate the AutoCAD Color Index (ACI) palette used by obj2cad-dxf.

Layer colors are written as true colors (group code 420) plus the nearest ACI color
(group code 62, which DXF requires). The 256-entry table comes from ezdxf (MIT).

Run:  python tools/dxf-template/gen_aci.py
Output: crates/obj2cad-dxf/src/aci.rs (committed; regenerate only on purpose).
"""

from pathlib import Path

from ezdxf.colors import DXF_DEFAULT_COLORS

OUT = Path(__file__).resolve().parents[2] / "crates" / "obj2cad-dxf" / "src" / "aci.rs"

rows = []
for i in range(0, 256, 8):
    rows.append("    " + " ".join(f"0x{c:06X}," for c in DXF_DEFAULT_COLORS[i : i + 8]))

OUT.write_text(
    "//! AutoCAD Color Index palette (generated by tools/dxf-template/gen_aci.py; do not edit).\n\n"
    "/// `ACI[i]` is ACI color `i` as 0xRRGGBB. Index 0 (ByBlock) and 256 (ByLayer) are not colors.\n"
    "pub const ACI: [u32; 256] = [\n" + "\n".join(rows) + "\n];\n\n"
    "/// Nearest ACI color (1..=255) to an RGB color, by squared distance.\n"
    "pub fn nearest([r, g, b]: [u8; 3]) -> i16 {\n"
    "    let (r, g, b) = (i32::from(r), i32::from(g), i32::from(b));\n"
    "    (1..256)\n"
    "        .min_by_key(|&i| {\n"
    "            let c = ACI[i];\n"
    "            let (cr, cg, cb) = ((c >> 16) as i32 & 255, (c >> 8) as i32 & 255, c as i32 & 255);\n"
    "            (cr - r).pow(2) + (cg - g).pow(2) + (cb - b).pow(2)\n"
    "        })\n"
    "        .unwrap_or(7) as i16\n"
    "}\n",
    newline="\n",
)
print(f"wrote {OUT}")
