import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { CircleAlert, ExternalLink } from "lucide-react";
import { motion } from "motion/react";
import { Button } from "@/components/ui/button";
import { CLI_URL, problemUrl } from "@/lib/errors";
export function FailedScreen({ name, explained, onPick, onRetry, }) {
    const e = explained;
    return (_jsx("main", { className: "paper flex h-dvh items-center justify-center overflow-hidden px-4 pt-[76px] pb-4", children: _jsxs(motion.div, { initial: { opacity: 0, y: 10 }, animate: { opacity: 1, y: 0 }, className: "panel flex max-h-full w-full max-w-[620px] flex-col gap-5 overflow-y-auto p-6", role: "alert", children: [_jsxs("div", { className: "flex gap-3 rounded-[4px] bg-danger-soft p-4 text-danger", children: [_jsx(CircleAlert, { className: "mt-0.5 size-5 shrink-0", "aria-hidden": "true" }), _jsxs("div", { className: "min-w-0", children: [_jsx("div", { className: "font-semibold", children: e.title }), _jsx("div", { className: "truncate text-[13.5px] text-fg-2", children: name })] })] }), _jsx("p", { className: "m-0 text-[14px]", children: e.action }), e.lines.length > 0 && (_jsxs("pre", { className: "num m-0 max-h-[240px] overflow-auto rounded-[4px] bg-panel-2 p-4 text-[12.5px] whitespace-pre-wrap text-fg", children: [e.lines.join("\n"), e.more && "\n…"] })), _jsxs("div", { className: "flex flex-wrap items-center gap-3", children: [onRetry && (_jsx(Button, { variant: "primary", onClick: onRetry, children: "Try again" })), _jsx(Button, { variant: onRetry ? "secondary" : "primary", onClick: onPick, children: "Choose a file\u2026" }), e.cli && (_jsx(Button, { variant: "link", asChild: true, children: _jsxs("a", { href: CLI_URL, target: "_blank", rel: "noreferrer", children: ["Command-line version ", _jsx(ExternalLink, {})] }) })), e.report && (_jsx(Button, { variant: "link", asChild: true, children: _jsxs("a", { href: problemUrl(e.title, e.lines.join("\n")), target: "_blank", rel: "noreferrer", children: ["Report a problem ", _jsx(ExternalLink, {})] }) }))] })] }) }));
}
