import { Fragment as _Fragment, jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowLeft, Check, ChevronDown, FolderOpen, FolderTree, Lock, RefreshCw } from "lucide-react";
import { Menu } from "@mantine/core";
import { Button } from "@/components/ui/button";
import { Tip } from "@/components/ui/tooltip";
import { Logo } from "@/components/brand";
import { bytes } from "@/lib/format";
import { shortcut } from "@/lib/utils";
export function TopBar({ file, offlineReady, onOpen, onOpenFolder, onBack, backLabel, watch, onWatch, }) {
    const meta = file && [bytes(file.size), file.exporter, file.files > 1 ? `${file.files} files` : null].filter(Boolean).join(" · ");
    return (_jsxs("header", { className: "pointer-events-none absolute inset-x-0 top-0 z-20 flex items-start gap-2 p-4", children: [_jsxs("div", { className: "panel pointer-events-auto flex h-11 shrink-0 items-center gap-2.5 pr-4 pl-3", children: [_jsx(Logo, { className: "size-5 text-accent" }), _jsx("span", { className: "text-[15px] font-semibold tracking-tight", children: "obj2cad" }), _jsx("span", { className: "num hidden text-[11.5px] text-fg-3 sm:inline", children: __APP_VERSION__ })] }), onBack && (_jsxs(Button, { className: "panel pointer-events-auto h-11 !rounded-[4px]", variant: "ghost", onClick: onBack, children: [_jsx(ArrowLeft, {}), _jsx("span", { className: "hidden sm:inline", children: backLabel })] })), file && (_jsxs(Menu, { position: "bottom-start", offset: 6, width: 260, classNames: { dropdown: "panel !p-1.5", item: "!rounded-[3px] !text-[13.5px]" }, children: [_jsx(Menu.Target, { children: _jsxs("button", { type: "button", className: "panel pointer-events-auto flex h-11 min-w-0 cursor-pointer items-center gap-3 px-4 text-left hover:border-fg-3 sm:max-w-[40vw]", children: [_jsx("span", { className: "truncate text-[14px] font-medium", children: file.name }), _jsx("span", { className: "num hidden truncate text-[12px] text-fg-3 sm:inline", children: meta }), _jsx(ChevronDown, { className: "size-4 shrink-0 text-fg-3" })] }) }), _jsxs(Menu.Dropdown, { children: [_jsx(Menu.Item, { leftSection: _jsx(FolderOpen, { className: "size-4" }), onClick: onOpen, children: "Open another file\u2026" }), _jsx(Menu.Item, { leftSection: _jsx(FolderTree, { className: "size-4" }), onClick: onOpenFolder, children: "Open a folder\u2026" }), watch !== null && (_jsx(Menu.Item, { leftSection: _jsx(RefreshCw, { className: "size-4" }), rightSection: watch ? _jsx(Check, { className: "size-3.5" }) : null, onClick: () => onWatch(!watch), children: "Reload when the file changes" }))] })] })), _jsx("div", { className: "min-w-0 flex-1" }), _jsxs("div", { className: "panel pointer-events-auto hidden h-11 items-center gap-2 px-4 text-[13px] text-fg-2 md:flex", children: [_jsx(Lock, { className: "size-3.5 text-exact", "aria-hidden": "true" }), "Local only", offlineReady && (_jsxs(_Fragment, { children: [_jsx("span", { className: "text-fg-3", children: "\u00B7" }), _jsx("span", { className: "size-1.5 rounded-full bg-exact", "aria-hidden": "true" }), "offline ready"] }))] }), _jsx(Tip, { label: `Open files (${shortcut("O")})`, side: "bottom", children: _jsxs(Button, { variant: "secondary", className: "pointer-events-auto h-11 shadow-panel", onClick: onOpen, "aria-label": "Open files", children: [_jsx(FolderOpen, {}), _jsx("span", { className: "hidden sm:inline", children: "Open" })] }) })] }));
}
